name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: "0 22 * * *" # cron表达式，Actions时区是UTC时间，所以要往前推8个小时

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Run 
      env:
        COOKIE: ${{ secrets.COOKIE }}
        token: ${{ secrets.token }}
        device_id: ${{ secrets.device_id }}
        glados: ${{ secrets.glados }}
      run: sbt run

